config/routes.rb
Rails.application.routes.draw do

  get 'reports/index'
  get 'stock_updates/index'
  # get 'adress_suppliers/show'
  root 'homes#index'
  # resources :application
  resources :product_colors
  resources :clients
  resources :products
  resources :suppliers
  resources :product_sizes
  resources :product_types
  resources :product_compositions
  resources :homes
  resources :address_suppliers, only: [:show]
  resources :contact_suppliers, only: [:show]
  resources :address_clients, only: [:show]
  resources :contact_clients, only: [:show]
  resources :stocks
  resources :stock_updates
  resources :stock_entries
  resources :stock_outs
  resources :stock_adjustments, only: [:edit]
  resources :reports
  get 'search', to: 'stock_updates#search'
  get 'report', to: 'reports#report'
  get 'withoutstock', to: 'reports#withoutstock'
  # get 'clients/masktel'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController

  include Paginable
   
  before_action :set_produtct_type, only: [:show, :edit, :update, :destroy]

  def index
    @product_types = ProductType.all.page(current_page).per(per_page)
  end

  def show
  end

  def edit
  end

  def new
    @product_type = ProductType.new
  end

  def create
    @product_type = ProductType.new(product_type_params)
    if @product_type.save
      redirect_to @product_type, notice: "Tipo de Produto criado com sucesso !!!"
    else
      render :new
    end
  end

  def update
    if @product_type.update(product_type_params)
      redirect_to @product_type, notice: "Tipo de Produto atualizado com sucesso !!!"
    else
      render :edit
    end
  end

  def destroy
    @product_type.destroy
    redirect_to @product_type, notice: "Tipo de Produto excluido com sucesso !!!"
  end

  private

  def set_produtct_type
    @product_type = ProductType.find(params[:id])
  end

  def product_type_params
    params.require(:product_type).permit(:id, :description)
  end

end

app/helpers/product_type_helper.rb
module ProductTypeHelper
end

app/views/product_types/create.html.erb
<h1>ProductType#create</h1>
<p>Find me in app/views/product_type/create.html.erb</p>

app/views/product_types/destroy.html.erb
<h1>ProductType#destroy</h1>
<p>Find me in app/views/product_type/destroy.html.erb</p>

app/views/product_types/edit.html.erb
<br>
<h5>Alterar Descrição do Tipo</h5>

<%= render 'layouts/form', resource: @product_type %>
<br>
<div class="link">
    <%= link_to 'Visualizar', @product_type, class: 'btn btn-secondary btn-sm' %>
    <%= link_to 'Lista', product_types_path, class: 'btn btn-warning btn-sm' %>
</div>

app/views/product_types/index.html.erb
<h5>Lista de Tipos de Produtos</h5>

<div class="pagination justify-content-end">
        <%= link_to_prev_page @product_types, '<< Pagina Anterior' %>
        <%= link_to_next_page @product_types, 'Proxima Pagina >>' %>
</div>

<%= render "layouts/principal", resource: @product_types %>

app/views/product_types/new.html.erb
<br>
<h5>Novo Tipo de Produto</h5>

<%= render 'layouts/form', resource: @product_type %>
<br>
<%= link_to 'Lista', product_types_path, class: 'btn btn-warning btn-sm' %>

app/views/product_types/show.html.erb
<br>
<h5>Tipo de Produto</h5>

<%= render "layouts/details", resource: @product_type %>

app/views/product_types/update.html.erb
<h1>ProductType#update</h1>
<p>Find me in app/views/product_type/update.html.erb</p>