config/routes.rb
Rails.application.routes.draw do

  get 'reports/index'
  get 'stock_updates/index'
  # get 'adress_suppliers/show'
  root 'homes#index'
  # resources :application
  resources :product_colors
  resources :clients
  resources :products
  resources :suppliers
  resources :product_sizes
  resources :product_types
  resources :product_compositions
  resources :homes
  resources :address_suppliers, only: [:show]
  resources :contact_suppliers, only: [:show]
  resources :address_clients, only: [:show]
  resources :contact_clients, only: [:show]
  resources :stocks
  resources :stock_updates
  resources :stock_entries
  resources :stock_outs
  resources :stock_adjustments, only: [:edit]
  resources :reports
  get 'search', to: 'stock_updates#search'
  get 'report', to: 'reports#report'
  get 'withoutstock', to: 'reports#withoutstock'
  # get 'clients/masktel'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord

    include PgSearch
    
    has_many :contact_clients, dependent: :destroy # possui muitod  endereços
    accepts_nested_attributes_for :contact_clients, reject_if: :all_blank, allow_destroy: true

    has_many :address_clients, dependent: :destroy # possui muitod  endereços
    accepts_nested_attributes_for :address_clients, reject_if: :all_blank, allow_destroy: true

    validates :client_name, :identification, presence: true
    
    validate :cpfcnpj

    scope :sorted_client, -> { order('client_name') }

    pg_search_scope :search, 
        against: %i[client_name],
        using: {tsearch: { prefix: true } }

    private

    def cpfcnpj
        if (identification.nil?)  ||  (identification.empty?)  || (identification.blank?)
            errors.add(:identification.to_s,  "CPF ou CNPJ não preenchido   !!!  ")
        else
            if identification.length ==  14
                cpf = CPF.new(identification)
            if !cpf.valid?
                    errors.add(cpf.formatted.to_s, "CPF  invalido   !!!  ")
                end
            else 
                if identification.length ==  18
                    cnpj = CNPJ.new(identification)
                    if !cnpj.valid?
                        errors.add(cnpj.formatted.to_s, "CNPJ  invalido   !!!  ")
                    end
                else 
                    errors.add(identification.to_s, "CPF ou CNPJ  invalido   !!!  ") 
                end 
            end
        end  
        
    end


end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  include Paginable

  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    if search_params[:q].blank?
      @clients = Client.sorted_client.page(current_page).per(per_page)
    else  
      @clients = Client.search(search_params[:q]).page(current_page).per(per_page)
    end
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end


  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to @client, notice: "Cliente Cadastrado com sucesso !!!"
    else
      render :new
    end
  end

  
  def update
    if @client.update(client_params)
      redirect_to @client, notice: "Cliente Atualizado com Sucesso !!!"
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to  clients_path, notice: "Cliente Excluido com sucesso !!!"
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def search_params
    params.permit(:q)
  end

  def client_params
    params.required(:client).permit(:id, :client_name, :identification, :description,
      address_clients_attributes: [:id, :street, :number, :complement, :neighborhood, :city, :state, :zip_code, :client_id, :_destroy],
      contact_clients_attributes: [:id, :client_name, :email, :telephone, :cell_phone, :description, :client_id, :_destroy])
  end

end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/clients/_address_client_fields.html.erb
<div class="nested-fields">

    <div class="addresses"> 
        <div class="field" >
            <%= f.label :street, "Rua :" %>
            <%= f.text_field :street %>
        </div>

        <div class="field" >
            <%= f.label :number, "Numero :" %>
            <%= f.text_field :number %>
        </div>

        <div class="field" >
            <%= f.label :complement, "Complemento :" %>
            <%= f.text_field :complement %>  
        </div>

        <div class="field" >
            <%= f.label :neighborhood, "Bairro :" %>
            <%= f.text_field :neighborhood %>
        </div>

        <div class="field">
            <%= f.label :city, "Cidade :" %>
            <%= f.text_field :city %>
        </div>

        <div class="field">
            <%= f.label :state, "Estado :" %>
            <%= f.select :state, Brazil.states, include_blank: "Selecione um Estado" %>
        </div>
        
        <div class="field">
            <%= f.label :zip_code, "Codigo Postal :" %>
            <%= f.text_field :zip_code %>
        </div>

    <%= link_to_remove_association "Excluir Endereço", f %>
    
    </div>


</div>
<br>

app/views/clients/_contact_client_fields.html.erb
<div class="nested-fields">

    <div class="addresses"> 
        <div class="field" >
            <%= f.label :contact_name, "Nome :" %>
            <%= f.text_field :client_name %>
        </div>

        <div class="field" >
            <%= f.label :email, "Email :" %>
            <%= f.text_field :email %>
        </div>

        <div class="field" >
            <%= f.label :telephone, "Telefone :" %>
            <%= f.text_field :telephone, class: 'phone-with-mask', placeholder: "(99)9999-9999", maxlength: "14" %>
        </div>

        <div class="field" >
            <%= f.label :cell_phone, "Celular :" %>
            <%= f.text_field :cell_phone, class: 'phone-with-mask', placeholder: "(99)99999-9999", maxlength: "15" %>
            
        </div>

        <div class="field">
            <%= f.label :description, "Observação :" %>
            <%= f.text_field :description, id: "obs" %>
        </div>

        <%= link_to_remove_association "Excluir Contato", f %>  

</div>
<br>

app/views/clients/_form_client.html.erb
<%= form_with(model: client, local: true) do |c| %>
    <% if client.errors.any? %>
        <div id="error_explanation">
            <h6><%= pluralize(client.errors.count, "erro(s)") %> Encontrado(s) no preenchimento do formulario !!</h6>

            <ul>
                <% client.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= c.label :client_name, "Nome :" %>
        <%= c.text_field :client_name %>
    </div>
  
    <div class="field">
        <%= radio_button_tag :document_type, "cpf" %> CPF
        <%= radio_button_tag :document_type, "cnpj" %> CNPJ  : 
        <%= c.text_field :identification, class: "cpf-cnpj-with-mask",
            placeholder: "Escolha CPF ou CNPJ" %> 
        <%= javascript_pack_tag 'clientradiobuttons' %>
    </div>

    <div class="field">
        <%= c.label :description, "Observação :" %>
        <%= c.text_field :description %>

    </div>

    <br>

    <div class="field">
        
        <%= c.fields_for :address_clients do |ac| %>
            <%= render "address_client_fields", f: ac %>
        <% end %>
        
    </div>
    
    <div class="links">
        <%= link_to_add_association "Adicionar Endereço", c, :address_clients %>
    </div>
    
    <br>

    <div class="field">
        
        <%= c.fields_for :contact_clients do |cc| %>
            <%= render "contact_client_fields", f: cc %>
        <% end %>
        
    </div>
    
    <div class="links">
            <%= link_to_add_association "Adicionar Contato", c, :contact_clients %>
    </div>
    <br>
    <div class="action">
        <%= c.submit "Salvar", class: 'btn btn-primary btn-sm' %>
        <%= link_to 'Cancelar', clients_path, class: 'btn btn-danger btn-sm' %>
    </div>
<% end %>

<%= javascript_pack_tag 'masktel' %>

app/views/clients/create.html.erb
<h1>Client#create</h1>
<p>Find me in app/views/client/create.html.erb</p>

app/views/clients/destroy.html.erb
<h1>Client#destroy</h1>
<p>Find me in app/views/client/destroy.html.erb</p>

app/views/clients/edit.html.erb
<br>
<h5>Alterar Cliente</h5>

<%= render 'form_client', client: @client %>

app/views/clients/index.html.erb
<h5>Lista de Cliente(s)</h5>

<div class="row">    
    <%= form_with(url: '/clients', method: :get, local: true) do %>
        <div class="column">  
            <p> <%= text_field_tag (:q) %>
                <%= submit_tag "Pesquisar", class: "btn btn-info btn-sm" %> 
            </p>  
        </div>
    <% end %> 
        <div  class="column pagination justify-content-end mt-2"> <p> <%= link_to_prev_page @clients, '<< Pagina Anterior'  %>
            <%= link_to_next_page @clients, 'Proxima Pagina >>' %> </p>
        </div>
</div>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>CPF / CNPJ</th>
            <th>OBS</th>
            <th>Endereço(s)</th>
            <th>Contato(s)</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @clients.each do |c| %>
            <tr>
                <td><%= c.client_name %></td>
                <td><%= c.identification %></td>
                <td><%= c.description %></td>

                <td><%= link_to ' Endereço(s) ', address_client_path(id: c.id) %> </td>
                <td><%= link_to ' Contato(s) ', contact_client_path(id: c.id) %> </td>
                        
                <td><%= link_to ' Visualizar ', client_path(c),  class: 'btn btn-secondary btn-sm'  %></td>
                <td><%= link_to ' Alterar ', edit_client_path(c), class: 'btn btn-success btn-sm' %></td>
                <td><%= link_to ' Excluir ', c, method: :delete, data: { confirm: "Voce tem certeza que quer Excluir?" }, class: 'btn btn-danger btn-sm' %> </td>
                
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'Novo Cliente', new_client_path, class: 'btn btn-info btn-sm' %>
<%= link_to 'Sair', homes_path, class: 'btn btn-dark btn-sm' %>

app/views/clients/new.html.erb
<br>
<h5>Novo Cliente </h5>
<%= render 'form_client', client: @client %>
<br>

app/views/clients/show.html.erb
<h5>Cliente</h5>

<p>
    <strong>Nome:</strong>
    <%= @client.client_name %>
</p>

<p>
    <strong>CPF / CNPJ:</strong>
    <%= @client.identification %>
</p>

<p>
    <strong>Observação:</strong>
    <%= @client.description %>
</p>
<h6><strong>Endereço</strong> </h6>

<ul>
    <% for @address_clients in @client.address_clients %>
        <li><%= [@address_clients.street, @address_clients.number, @address_clients.complement,
                 @address_clients.neighborhood, @address_clients.city, 
                 @address_clients.state, @address_clients.zip_code].join(", ")  %></li>
    <% end %>
</ul>

<h6><strong>Contato</strong> </h6>

<ul>
    <% for @contact_clients in @client.contact_clients %>
        <li><%= [@contact_clients.client_name, @contact_clients.email, @contact_clients.telephone,
                 @contact_clients.cell_phone, @contact_clients.description].join(", ") %> </li>
    <% end %>
</ul>
<br>
<%= link_to ' Alterar ', edit_client_path(@client), class: 'btn btn-primary btn-sm' %>    
<%= link_to ' Lista ', clients_path, class: 'btn btn-warning btn-sm' %>
<%= link_to 'Novo Cliente', new_client_path, class: 'btn btn-info btn-sm' %>
<%= link_to 'Sair', homes_path, class: 'btn btn-dark btn-sm' %>

app/views/clients/update.html.erb
<h1>Client#update</h1>
<p>Find me in app/views/client/update.html.erb</p>