config/routes.rb
Rails.application.routes.draw do

  get 'reports/index'
  get 'stock_updates/index'
  # get 'adress_suppliers/show'
  root 'homes#index'
  # resources :application
  resources :product_colors
  resources :clients
  resources :products
  resources :suppliers
  resources :product_sizes
  resources :product_types
  resources :product_compositions
  resources :homes
  resources :address_suppliers, only: [:show]
  resources :contact_suppliers, only: [:show]
  resources :address_clients, only: [:show]
  resources :contact_clients, only: [:show]
  resources :stocks
  resources :stock_updates
  resources :stock_entries
  resources :stock_outs
  resources :stock_adjustments, only: [:edit]
  resources :reports
  get 'search', to: 'stock_updates#search'
  get 'report', to: 'reports#report'
  get 'withoutstock', to: 'reports#withoutstock'
  # get 'clients/masktel'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stock_out.rb
class StockOut < ApplicationRecord

  belongs_to :client, optional: true
  belongs_to :stock

  validates :date_out, :type_out, presence: true
  validates :client_id, presence: true, if: :type_out_client?

  before_validation :check_quantity

  after_create :update_quantity

  after_destroy :change_quantity

  private

  def type_out_client?
    type_out > "2"
  end

  def check_quantity
    @qtd = stock.quantity
    if (quantity.blank?)
      errors.add(:quantity.to_s, ", Quantidade Nâo foi preenchida")
    else 
        if  quantity  >  stock.quantity
            errors.add("Quantidade #{quantity.to_s} informada, ",  "Nâo Pode ser Maior  que #{stock.quantity} ")
        else
            if quantity < 1
                errors.add(:quantity.to_s, ", Quantidade Nâo Pode ser menor que 1")
            end
        end
    end
  end

  def update_quantity 
      new_quantity = stock.quantity - quantity
      stock.update(quantity: new_quantity)
  end

  def change_quantity
    new_quantity = stock.quantity + quantity
    stock.update(quantity: new_quantity)
  end

end

app/controllers/stock_outs_controller.rb
class StockOutsController < ApplicationController

  include Paginable

  before_action :set_stock_out, only: [:show, :edit, :update, :destroy]
  before_action :prepare_form_type_out

  def index
    @stock_outs = StockOut.order(date_out: :desc).page(current_page).per(per_page)
  end

  def show
  end

  def new
    prepare_form_stock_out
    @stock_out = StockOut.new
    get_stock
  end

  def edit
    prepare_form_stock_out
  end

  def create
    qtd1 = @qtd.to_i
    @stock_out = StockOut.new(stock_out_params) 
    
    if @stock_out.save
      redirect_to @stock_out, notice: "Saida do Estoque criado com sucesso !!! "
    else
      prepare_form_stock_out
      params[:stock_cod] = @stock_out.stock_id
      get_stock
      render  :new
    end
  end

  def update
    if @stock_out.update(stock_out_params)
      redirect_to @stock_out, notice: "Saida do Estoque alterado com sucesso !!! "
    else
      prepare_form_stock_out
      render :edit
    end
  end

  def destroy
    @stock_out.destroy
    redirect_to stock_outs_url, notice: "Saida do Estoque excluido com sucesso"
  end

  
  private

  def set_stock_out
    @stock_out = StockOut.find(params[:id])
    prepare_form_type_out
    params[:stock_cod] = @stock_out.stock_id
    @stocks = Stock.where(id: params[:out_cod])
    get_stock 
  end

  def get_stock 
    stock_list = Stock.where(id: params[:out_cod])  if params[:out_cod] 
    stock_list = Stock.where(id: params[:stock_cod])  if params[:stock_cod]   
    stock_list = Stock.all  if stock_list.blank?

    @stockprod = stock_list.map do |stock|
        @qtd = stock.quantity
        description = [
            stock.supplier.supplier_name,
            stock.product.product_type.description,
            stock.product.description,
            stock.product.product_color.description,
            stock.product.product_composition.description,
            stock.product.product_size.description
            ].join(", ")     
        [description, stock.quantity, stock.id ]
    end
  end 

  def stock_out_params
    params.require(:stock_out).permit(:id, :order_number, :client_id, :quantity, :date_out, :description, :stock_id, :type_out, :product_id, :out_cod, :q)
  end

  def prepare_form_stock_out
      @clients = Client.all.map {|client| [client.client_name , client.id]}
  end

  def prepare_form_type_out
    @typeouts = [["Material para Fabricação", 0], ["Devolução para Fornecedor", 1], ["Devolução Estoque para Fornecedor", 2], ["Material para Cliente", 3]]
  end
  
end

app/helpers/stock_out_helper.rb
module StockOutHelper
end

app/views/stock_outs/_form_out.html.erb
<%= form_with(model: stock_out, local: true) do |so| %>
   
    <% if stock_out.errors.any? %>
        <div id="error_explanation">
            <h6><%= pluralize(stock_out.errors.count, "erro(s)") %> Encontrado(s) no preenchimento do formulario !!</h6>
            <ul>
                <% stock_out.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="field">
        <%= so.label :stock_id, "Produto" %>
        <%= so.select :stock_id, @stockprod %>
    </div>

    <div class="field">
        <%= so.label :type_entry, "Tipo de Saida " %>
        <%= so.select :type_out, @typeouts, 
            include_blank: "Selecione um tipo de saida" %> 
    </div>

    <div class="field">        
        <%= so.label :date_out, "Data da Saida" %>
        <%= so.date_field :date_out, max: Date.today %>
    </div>
    
    <div class="field">
        <%= so.label :invoice, "Numero do Pedido" %>
        <%= so.text_field :order_number %>  
    </div>

     <div class="field">
        <%= so.label :clientt_id, "Cliente :" %>
        <%= so.select :client_id, @clients, include_blank: "selecione um cliente..." %> 
    </div>

    <div class="field">
        <%= so.label  "Quantidade no Estoque : " %>
        <strong> <%= so.label  @qtd  %> </strong>
    </div>


    <div class="field">
        <%= so.label :quantity, "Quantidade" %>
        <%= so.number_field :quantity, placeholder: "0" %>
    </div>

    <div class="field">
        <%= so.label :description, "Obsorvação :" %>
        <%= so.text_field :description %>
    </div>
    
    <br>
    <div class="actions">
        <%= so.submit "Salvar", class: "btn btn-primary btn-sm",  onClick: "convert();" %>
        <%= link_to 'Cancelar', stock_updates_path, class: 'btn btn-danger btn-sm' %>
    </div>
<% end %>

app/views/stock_outs/create.html.erb
<h1>StockOut#create</h1>
<p>Find me in app/views/stock_out/create.html.erb</p>

app/views/stock_outs/destroy.html.erb
<h1>StockOut#destroy</h1>
<p>Find me in app/views/stock_out/destroy.html.erb</p>

app/views/stock_outs/edit.html.erb
<p id="notice"><%= notice %></p>
<h5>Alterar Saida do Estoque</h5>

<%= render "form_out", stock_out: @stock_out %>

app/views/stock_outs/index.html.erb
<h5>Lista de Saidas do Estoque</h5>

<div class="pagination justify-content-end">
        <%= link_to_prev_page @stock_outs, '<< Pagina Anterior' %>
        <%= link_to_next_page @stock_outs, 'Proxima Pagina >>' %>
</div>

 <table>
    <thead>
        <tr>
            <th>Data Saida</th>
            <th>Produto</th>
            <th>Fornecedor </th>
            <th>Qtd.</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @stock_outs.each do |so| %>
            <tr>
                <td><%= format_date(so.date_out) %></td>
                <td><%= [so.stock.product.product_type.description, so.stock.product.description, 
                            so.stock.product.product_color.description].join(", ") %></td>                        
                <td><%= so.stock.supplier.supplier_name %></td>                        
                <td><strong><%= format_quantity(so.quantity) %></strong> </td>
                <td><%= link_to ' Visualizar ', stock_out_path(so),  class: 'btn btn-secondary btn-sm'  %></td>
                <td><%= link_to ' Alterar ', edit_stock_out_path(so), class: 'btn btn-success btn-sm' %></td>
                <td><%= link_to ' Excluir ', so, method: :delete, data: { confirm: "Voce tem certeza que quer Excluir ?" }, class: 'btn btn-danger btn-sm' %> </td>      
            </tr>
        <% end %>
    </tbody>
</table>
<br>
<%= link_to 'Sair', homes_path, class: 'btn btn-dark btn-sm' %>

app/views/stock_outs/new.html.erb
<p id="notice"><%= notice %></p>
<h5>Saida(s) do Estoque</h5>

<%= render "form_out", stock_out: @stock_out %>

app/views/stock_outs/show.html.erb
<h5>Saida do Estoque</h5>

<p>
    <strong>Produto:</strong>
    <%= [@stock_out.stock.product.description, @stock_out.stock.product.product_color.description, 
         @stock_out.stock.product.product_composition.description, 
         @stock_out.stock.product.product_size.description].join(", ") %>
</p>

<p>
    <strong>Fornecedor:</strong>
    <%= @stock_out.stock.supplier.supplier_name %>
</p>

<p>
    <strong>Referencia:</strong>
    <%= @stock_out.stock.reference %>
</p>

<p>
    <strong>Tipo de Saidaa:</strong>
    <%= @typeouts[@stock_out.type_out.to_i][0] %>
</p>

<p>
    <strong>Data da Saida:</strong>
    <%= format_date(@stock_out.date_out) %>
</p>

<p>
    <strong>Numero do Pedido:</strong>
    <%= @stock_out.order_number %>
</p>

<p>
    <strong>Cliente:</strong>
    <%= @stock_out.client&.client_name %>
</p>

<p>
    <strong>Quantidade:</strong>
    <%= @stock_out.quantity %>
</p>

<p>
    <strong>Observação:</strong>
    <%= @stock_out.description %>
</p>

<p>
    <strong>Data Atualização:</strong>
    <%= format_date_hours(@stock_out.updated_at) %>
</p>

<br>
<%= link_to ' Alterar ', edit_stock_out_path(@stock_out), class: 'btn btn-primary btn-sm' %>    
<%= link_to 'Nova Saida do Estoque', stock_updates_path, class: 'btn btn-info btn-sm' %>
<%= link_to 'Sair', homes_path, class: 'btn btn-dark btn-sm' %>

app/views/stock_outs/update.html.erb
<h1>StockOut#update</h1>
<p>Find me in app/views/stock_out/update.html.erb</p>