config/routes.rb
Rails.application.routes.draw do

  get 'reports/index'
  get 'stock_updates/index'
  # get 'adress_suppliers/show'
  root 'homes#index'
  # resources :application
  resources :product_colors
  resources :clients
  resources :products
  resources :suppliers
  resources :product_sizes
  resources :product_types
  resources :product_compositions
  resources :homes
  resources :address_suppliers, only: [:show]
  resources :contact_suppliers, only: [:show]
  resources :address_clients, only: [:show]
  resources :contact_clients, only: [:show]
  resources :stocks
  resources :stock_updates
  resources :stock_entries
  resources :stock_outs
  resources :stock_adjustments, only: [:edit]
  resources :reports
  get 'search', to: 'stock_updates#search'
  get 'report', to: 'reports#report'
  get 'withoutstock', to: 'reports#withoutstock'
  # get 'clients/masktel'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  include PgSearch
  
  belongs_to :product_type
  belongs_to :product_composition
  belongs_to :product_color
  belongs_to :product_size
 
  validates :description, presence: true
  
  validates :description, uniqueness: {
    scope: [:product_type_id, :product_color_id, :product_composition_id, :product_size_id],
    case_sensitive: false, message: "Produto já existe"
  }

  scope :without_stock, -> { joins(:product_type).where(
          'NOT EXISTS (:product_id)',
          product_id: Stock.where('products.id = stocks.product_id')          
        ).order('product_types.description', 'products.description') }
 

  pg_search_scope :search, 
      against: %i[description],
      associated_against: { product_type: %i[description] },
      using: {tsearch: { prefix: true } }
        
  before_create do
    self.status = "active"
  end

end

app/models/product_type.rb
class ProductType < ApplicationRecord

    validates :description, presence: true, uniqueness: { case_sensitive: false,
                message: "do Tipo já existe !!!" }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  include Paginable
  
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    if search_params[:q].blank?
      @products = Product.all.page(current_page).per(per_page)
    else
      @products = Product.search(search_params[:q]).page(current_page).per(per_page)
    end
  end

  def show
    prepare_form
  end

  def new
    prepare_form
    @product = Product.new
  end

  def edit
    prepare_form
  end

  def create
    @product = Product.new(product_params) 
    if @product.save
      redirect_to @product, notice: "Produto salvo com sucesso !!! "
    else
      prepare_form
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: "Produto alterado com sucesso !!! "
    else
      prepare_form
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: "Produto excluido com sucesso"
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def search_params
    params.permit(:q)
  end

  def product_params
    params.require(:product).permit(:product_type_id, :description, :product_composition_id,
                   :product_color_id, :product_size_id, :status)
  end

  def prepare_form
    @product_types = ProductType.order(:description).all.map { |type| [type.description, type.id] }
    @product_colors = ProductColor.order(:description).all.map { |color| [color.description, color.id] }
    @product_sizes = ProductSize.order(:description).all.map { |size| [size.description, size.id] }
    @product_compositions = ProductComposition.order(:description).all.map { |composition| [composition.description, composition.id] }
    
  end

end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_form_product.html.erb
<%= form_with(model: product, local: true) do |p| %>
    <% if product.errors.any? %>
        <div id="error_explanation">
            <h6><%= pluralize(product.errors.count, "erro(s)") %> Encontrado(s) no preenchimento do formulario !!</h6>

            <ul>
                <% product.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

     <div class="field">
        <%= p.label :product_type_id, "Tipo de Produto: " %>
        <%= p.select :product_type_id, @product_types, include_blank: "Selecione um produto...", required: true %>
    </div>

    <div class="field">
        <%= p.label :description, "Descrição :" %>
        <%= p.text_field :description %>
    </div>

     <div class="field">
        <%= p.label :product_color_id, "Cor : " %>
        <%= p.select :product_color_id, @product_colors, include_blank: "Selecione uma cor..." %>
    </div>

     <div class="field">
        <%= p.label :product_composition_id, "Composição : " %>
        <%= p.select :product_composition_id, @product_compositions, include_blank: "Selecione uma composição..." %>
    </div>

     <div class="field">
        <%= p.label :product_size_id, "Tamanho : " %>
        <%= p.select :product_size_id, @product_sizes, include_blank: "Selecione um tamanho..." %>
    </div>

    <br>
    <div class="action">
        <%= p.submit "Salvar", class: 'btn btn-primary btn-sm' %>
        <%= link_to 'Cancelar', products_path, class: 'btn btn-danger btn-sm' %>
    </div>
<% end %>

app/views/products/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Product#destroy</h1>
<p>Find me in app/views/product/destroy.html.erb</p>

app/views/products/edit.html.erb
<br>
<h5>Alterar Produto</h5>

<%= render 'form_product', product: @product %>

app/views/products/index.html.erb
<h5>Lista de Produto(s)</h5>

<div class="row">    
    <%= form_with(url: '/products', method: :get, local: true) do %>
        <div class="column">  
            <p> <%= text_field_tag :q %>
                <%= submit_tag "Pesquisar", data: {disable_with: 'Buscando....' }, class: "btn btn-info btn-sm" %> 
            </p>  
        </div>
    <% end %> 
        <div  class="column pagination justify-content-end mt-2"> <p> <%= link_to_prev_page @products, '<< Pagina Anterior'  %>
            <%= link_to_next_page @products, 'Proxima Pagina >>' %> </p>
        </div>
</div>

<table>
    <thead>
        <tr>
            <th>Produto</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @products.each do |p| %>
            <tr>
                <td><%= [p.product_type.description, p.description, p.product_composition.description,
                         p.product_color.description, p.product_size.description].join(", ") %></td>
                <td><%= link_to ' Visualizar ', product_path(p),  class: 'btn btn-secondary btn-sm'  %></td>
                <td><%= link_to ' Alterar ', edit_product_path(p), class: 'btn btn-success btn-sm' %></td>
                <td><%= link_to ' Excluir ', p, method: :delete, data: { confirm: "Voce tem certeza que quer Excluir ?" }, class: 'btn btn-danger btn-sm' %> </td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_product_path, class: 'btn btn-info btn-sm' %>
<%= link_to 'Sair', homes_path, class: 'btn btn-dark btn-sm' %>

app/views/products/new.html.erb
<br>
<h5>Novo Produto </h5>
<%= render 'form_product', product: @product %>
<br>

app/views/products/show.html.erb
<h5>Produto</h5>

<p>
    <strong>Tipo de Produto:</strong>
    <%= @product.product_type.description %>
</p>

<p>
    <strong>Descrição:</strong>
    <%= @product.description %>
</p>

<p>
    <strong>Cor:</strong>
    <%= @product.product_color.description %>
</p>

<p>
    <strong>Composição:</strong>
    <%= @product.product_composition.description %>
</p>

<p>
    <strong>Tamanho:</strong>
    <%= @product.product_size.description %>
</p>

<p>
    <strong>Status:</strong>
    <%= @product.status %>
</p>

<br>
<%= link_to ' Alterar ', edit_product_path(@product), class: 'btn btn-primary btn-sm' %>    
<%= link_to 'Novo Produto', new_product_path, class: 'btn btn-info btn-sm' %>
<%= link_to ' Lista ', products_path, class: 'btn btn-warning btn-sm' %>
<%= link_to 'Criar Estoque', new_stock_path(prod_id: @product.id), class: 'btn btn-info btn-sm' %>
<%= link_to 'Sair', homes_path, class: 'btn btn-dark btn-sm' %>

app/views/products/update.html.erb
<h1>Product#update</h1>
<p>Find me in app/views/product/update.html.erb</p>